name: chiweb_vuebuild

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: package
          zip dist
      - name: cleanup
        uses: actions/upload-artifact@master
        with:
            name: dist.zip